Fix Cons clone_to_process
The `head` element was not being pushed when the `tail` was a non-empty
list as `current` was switched to the `tail`'s `Cons` cell before `head`
was pushed to the `builder`.

```
[lumen_runtime/src/process.rs:121] arguments = Term([Term(:'normal', id: 9) | Term(Nil)])
[lumen_runtime/src/process.rs:123] heap_arguments = Term([Term(:'normal', id: 9) | Term(Nil)])
[lumen_runtime/src/otp/erlang/tests/spawn_3/with_atom_module/with_atom_function/with_non_empty_proper_list_arguments/with_loaded_module/with_exported_function.rs:28] arguments = Term([Term(0) | Term([Term(1) | Term([Term(2) | Term(Nil)])])])
[lumen_runtime/src/process.rs:121] arguments = Term([Term(0) | Term([Term(1) | Term([Term(2) | Term(Nil)])])])
[lumen_runtime/src/process.rs:123] heap_arguments = Term([Term(1) | Term([Term(2) | Term([Term(2) | Term(Nil)])])])
[lumen_runtime/src/code.rs:102] argument_list = Term([Term(:'normal', id: 9) | Term(Nil)])
[lumen_runtime/src/code.rs:102] argument_list = Term([Term(1) | Term([Term(2) | Term([Term(2) | Term(Nil)])])])
thread 'otp::erlang::tests::spawn_3::with_atom_module::with_atom_function::with_non_empty_proper_list_arguments::with_loaded_module::with_exported_function::without_arity_when_run_exits_undef' panicked at 'assertion failed: `(left == right)`
  left: `Exception { class: Exit, reason: Term(:'undef', id: 11), stacktrace: Some(Term([Term(Boxed(0x109ac0070 => Term(Tuple(Term(:'erlang', id: 7), Term(:'+', id: 10), Term([Term(1) | Term([Term(2) | Term([Term(2) | Term(Nil)])])]), Term(Nil))))) | Term(Nil)])), file: "lumen_runtime/src/code.rs", line: 127, column: 26 }`,
 right: `Exception { class: Exit, reason: Term(:'undef', id: 11), stacktrace: Some(Term([Term(Boxed(0x109ac00a8 => Term(Tuple(Term(:'erlang', id: 7), Term(:'+', id: 10), Term([Term(0) | Term([Term(1) | Term([Term(2) | Term(Nil)])])]), Term(Nil))))) | Term(Nil)])), file: "lumen_runtime/src/otp/erlang/tests/spawn_3/with_atom_module/with_atom_function/with_non_empty_proper_list_arguments/with_loaded_module/with_exported_function.rs", line: 62, column: 21 }`', lumen_runtime/src/otp/erlang/tests/spawn_3/with_atom_module/with_atom_function/with_non_empty_proper_list_arguments/with_loaded_module/with_exported_function.rs:66:17
```

The `builder.push(current.head)` was also missing from the improper list
path.

Fixes these two made `build.push(current.head)` occur on all branches,
so lift it out and the logic becomes simpler:

1. If end of list (nil), `finish`.
2. If tip of list (Cons), continue.
3. If anything else, improper end, `finish_with` that improper.