Build lumen_rt_minimal, but don't test directly
`cargo test --package lumen_rt_minimal` can't find the panic libs to define `___rust_start_panic`, which makes sense because the linker in `lumen` does that, but I don't want to figure out how to make `cargo test`'s linking do that now.

```
= note: Undefined symbols for architecture x86_64:
            "___rust_start_panic", referenced from:
                _rust_panic in libstd-858c20f5a0702910.rlib(std-858c20f5a0702910.std.21u5irid-cgu.0.rcgu.o)
            "___rust_panic_cleanup", referenced from:
                std::panicking::try::cleanup::hd895f7beef0a7dad in libstd-858c20f5a0702910.rlib(std-858c20f5a0702910.std.21u5irid-cgu.0.rcgu.o)
            "_rust_eh_personality", referenced from:
                core::ops::function::FnOnce::call_once::h40c39e07a9070a76 in lumen_rt_minimal-b8b66542de061c5d.188t3h4xj3akqwq1.rcgu.o
                core::ops::function::FnOnce::call_once::h51d5195e598c30e4 in lumen_rt_minimal-b8b66542de061c5d.188t3h4xj3akqwq1.rcgu.o
                core::ops::function::FnOnce::call_once::he85923b3c4571af1 in lumen_rt_minimal-b8b66542de061c5d.188t3h4xj3akqwq1.rcgu.o
                core::result::Result$LT$T$C$E$GT$::unwrap::h82c0b710b82fa85c in lumen_rt_minimal-b8b66542de061c5d.19ga93raw352159x.rcgu.o
                core::option::Option$LT$T$GT$::map::hae86c3840667def2 in lumen_rt_minimal-b8b66542de061c5d.1txep9je13m4r2yt.rcgu.o
                lumen_rt_minimal::sys::cpus::tests::env_var::_$u7b$$u7b$closure$u7d$$u7d$::h5d43e0740bbd4e14 in lumen_rt_minimal-b8b66542de061c5d.5rajjdtfc73m6gz.rcgu.o
                core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h13f02ad6ec46a67f in libstd-858c20f5a0702910.rlib(std-858c20f5a0702910.std.21u5irid-cgu.0.rcgu.o)
                ...
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```