Only test chrome
Firefox error:

```
driver status: signal: 9
driver stdout:
    1567638578782	mozrunner::runner	INFO	Running command:
"/usr/local/bin/firefox" "-marionette" "-headless" "-foreground"
"-no-remote" "-profile" "/tmp/rust_mozprofile.fscU2rNKzUGq"
    1567638579160	addons.webextension.screenshots@mozilla.org
WARN	Loading extension 'screenshots@mozilla.org': Reading manifest:
Invalid extension permission: mozillaAddons
    1567638579160	addons.webextension.screenshots@mozilla.org
WARN	Loading extension 'screenshots@mozilla.org': Reading manifest:
Invalid extension permission: telemetry
    1567638579160	addons.webextension.screenshots@mozilla.org
WARN	Loading extension 'screenshots@mozilla.org': Reading manifest:
Invalid extension permission: resource://pdf.js/
    1567638579160	addons.webextension.screenshots@mozilla.org
WARN	Loading extension 'screenshots@mozilla.org': Reading manifest:
Invalid extension permission: about:reader*
    1567638580578	Marionette	INFO	Listening on port 40147
    A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set,
shutting down
    1567638583005	Marionette	INFO	Stopped listening on
port 40147
driver stderr:
    *** You are running in headless mode.
    (firefox:5725): Gtk-WARNING **: 23:09:38.812: Locale not supported
by C library.
    	Using the fallback 'C' locale.
    [Parent 5725, Gecko_IOThread] WARNING: pipe error (67): Connection
reset by peer: file
/builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc,
line 358

error: invalid type: null, expected a string at line 1 column 13
error: test failed, to rerun pass '--test web'
```