Compiling `erlang:abs/1` tests shows bugs with numbers
With only integers:

-module(init).
-compile({no_auto_import,[abs/1]}).
-export([start/0]).
-import(erlang, [abs/1, display/1]).

start() ->
%%  display(abs(-2.0)),
  display(abs(-1)),
%%  display(abs(0.0)),
  display(abs(0)),
  display(abs(1)).
%%  display(abs(2.0)).

It thinks the integer terms are normal i64:

stderr =    Compiling
tests/erlang/abs_1/with_number_returns_non_negative/init.erl
error: 'eir.call' op operand #0 must be any term type, but got 'i64'

module @init {
  eir.func @lumen_eh_personality() -> i32 attributes {std.varargs =
true}
  eir.func @"init:start/0"() -> !eir.term attributes {personality =
@lumen_eh_personality} {
    %0 = eir.constant.int 1 : i64
    %1 = eir.call @"erlang:-/1"(%0) : (i64) -> !eir.term
    eir.br ^bb1(%1 : !eir.term)
  ^bb1(%2: !eir.term):  // pred: ^bb0
    %3 = eir.call @"erlang:abs/1"(%2) : (!eir.term) -> !eir.term
    eir.br ^bb2(%3 : !eir.term)
  ^bb2(%4: !eir.term):  // pred: ^bb1
    %5 = eir.call @"erlang:display/1"(%4) : (!eir.term) -> !eir.term
    eir.br ^bb3(%5 : !eir.term)
  ^bb3(%6: !eir.term):  // pred: ^bb2
    %7 = eir.constant.int 0 : i64
    %8 = eir.call @"erlang:abs/1"(%7) : (i64) -> !eir.term
    eir.br ^bb4(%8 : !eir.term)
  ^bb4(%9: !eir.term):  // pred: ^bb3
    %10 = eir.call @"erlang:display/1"(%9) : (!eir.term) -> !eir.term
    eir.br ^bb5(%10 : !eir.term)
  ^bb5(%11: !eir.term): // pred: ^bb4
    %12 = eir.constant.int 1 : i64
    %13 = eir.call @"erlang:abs/1"(%12) : (i64) -> !eir.term
    eir.br ^bb6(%13 : !eir.term)
  ^bb6(%14: !eir.term): // pred: ^bb5
    %15 = eir.call @"erlang:display/1"(%14) : (!eir.term) -> !eir.term
    eir.return %15 : !eir.term
  }
}loc("tests/erlang/abs_1/with_number_returns_non_negative/init.erl":1:1):
error: module verification error

For just floats.

-module(init).
-compile({no_auto_import,[abs/1]}).
-export([start/0]).
-import(erlang, [abs/1, display/1]).

start() ->
  display(abs(-2.0)),
%%  display(abs(-1)),
  display(abs(0.0)),
%%  display(abs(0)),
%%  display(abs(1)).
  display(abs(2.0)).

 it says the type isn't a float:

stderr =    Compiling
tests/erlang/abs_1/with_number_returns_non_negative/init.erl
error: expected floating point type
Assertion failed: (succeeded(ConcreteT::verifyConstructionInvariants(
generateUnknownStorageLocation(ctx), args...))), function get, file
/Users/paulschoenfelder/src/github.com/bitwalker/llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h,
line 62.
', native_implemented/otp/tests/erlang/abs_1.rs:50:5
note: run with `RUST_BACKTRACE=1` environment variable to display a
backtr

This could of course be a similar bug to the integer one where it is
using LLVM's f32 or f64 instead of the term version.